name: wp-toolkit
type: php
docroot: src
php_version: '8.1'
webserver_type: nginx-fpm
router_http_port: '80'
router_https_port: '443'
xdebug_enabled: true
additional_hostnames: []
additional_fqdns: []
database:
  type: mariadb
  version: '10.4'
hooks:
  post-start:
    - exec: sudo apt-get update && sudo apt-get install subversion -y
    - exec: ./bin/install-wp-tests.sh wordpress_test root root db latest
use_dns_when_possible: true
composer_version: '2'
web_environment:
  - XDEBUG_MODE=coverage
nodejs_version: '20'
