on:
  push:
    branches:
      - master
      - develop
  pull_request:

name: Tests

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: php-actions/composer@v5
        with:
          php_version: 7.3

      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        env:
          REQUIRE_DEV: true
        with:
          args: analyse

  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine composer cache directory
        shell: bash
        run: "echo \"COMPOSER_CACHE_DIR=$(composer config cache-dir)\" >> $GITHUB_ENV"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - uses: php-actions/composer@v5
        with:
          php_version: 7.3

      - name: PHPCS
        uses: chekalsky/phpcs-action@v1
        with:
          phpcs_bin_path: ./vendor/bin/phpcs

  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest

    services:
      mysql:
          image: mysql:5.7
          env:
              MYSQL_ROOT_PASSWORD: root
              MYSQL_DATABASE: wordpress_test
          ports:
              - 3306:3306
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@v5
        with:
          php_version: 7.3

      - name: Determine composer cache directory
        shell: bash
        run: "echo \"COMPOSER_CACHE_DIR=$(composer config cache-dir)\" >> $GITHUB_ENV"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      # Specify PHP 7.3 version to run PHPUnit and prevent Github action error (PHPUnit 7.* isn't compatible w/ PHP 8.*).
      - name: Setup PHP 7.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
          coverage: xdebug

      - name: Clean old WP Tests
        run: mysql --host 127.0.0.1 --port 3306 -uroot -proot -e "DROP DATABASE IF EXISTS wordpress_test;" && rm -fr /tmp/wordpress*

      - name: Install WP Tests
        run: ./bin/install-wp-tests.sh wordpress_test root root 127.0.0.1 latest

      - name: PHPUnit
        run: XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover='coverage.xml'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          fail_ci_if_error: true
          path_to_write_report: ./codecov_report.txt
          verbose: true
